#### 1. Import the numpy package under the name `np` (★☆☆)

In [55]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([5.05528123e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.64108274e-066, 1.16188963e+165, 5.28206026e-091,
       1.10618148e-046, 4.34243033e-315])

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
list = np.empty(10)
list[4] = 1

print(list)

[4.64914744e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 1.00000000e+000 3.43974401e+175 4.99047047e+174 4.47321964e-090
 6.18190328e+169 6.89568164e-310]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
listRange = np.arange(10,50)
print(listRange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
listRange[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
np.random.randint(0,9,9).reshape(3,3)

array([[4, 0, 2],
       [7, 5, 8],
       [2, 4, 5]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [27]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
np.random.randint(0,16,27).reshape(3,3,3)

array([[[14,  1, 14],
        [ 7, 14,  1],
        [ 8,  2, 14]],

       [[10,  1,  3],
        [ 7,  7, 14],
        [14,  7,  6]],

       [[12,  4, 12],
        [ 9,  1,  8],
        [ 2,  7,  7]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [35]:
listFind = np.random.randint(0,11,100).reshape(10,10)
print(listFind)
print('max is: ',np.max(listFind))
print('min is: ',np.min(listFind))

[[ 3  2  7  4  3  0 10  9  1  3]
 [ 4  6  7  1  5  8 10  7 10  9]
 [ 2  3  3  5  9  2  7  2  5  6]
 [ 2 10  9  1  6  6 10  4  6  4]
 [ 1  8  1  2  4  9  1  7  2  6]
 [ 5  1 10  9  9  5 10  1  1  9]
 [ 0  9  4  3  5  3  6  1  7  6]
 [ 9  7  5  2  0  3  9  5  0  9]
 [ 1  0  3  3  9  5  9  8  7  2]
 [ 9  4  9  5  9  6  5  2  2 10]]
max is:  10
min is:  0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
np.mean(np.random.randint(0,11,30))

5.4

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [38]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [44]:
listValues = np.zeros((5,5),dtype=int)

for i in range(4):
  listValues[i+1,i]=i+1

print(listValues)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
listValues = np.zeros((5,5),dtype=int)

listValues[::2,::2]=1
listValues[1::2,1::2]=1


print(listValues)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [50]:
listShape = np.arange(6*7*8)
index = np.unravel_index(100, listShape.shape)
print(index)

(100,)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [54]:
listTile= np.array([[0,1],[1,0]])
print(np.tile(listTile,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [56]:
listRandom = np.random.randint(0,11,25).reshape(5,5)

mn = np.mean(listRandom)
std = np.std(listRandom)

listNormalized = (listRandom - mn) / std

print(listNormalized)

[[ 0.94451869 -0.89545279  0.94451869  0.94451869 -1.50877661]
 [ 0.63785678 -1.2021147  -1.50877661  1.2511806  -1.2021147 ]
 [-1.2021147   1.2511806   0.02453295 -0.58879087  0.02453295]
 [ 0.63785678  0.63785678 -0.58879087  1.55784252  0.33119487]
 [ 1.2511806  -0.58879087 -0.89545279 -1.2021147   0.94451869]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [57]:
listColors = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

<ipython-input-57-8e298ab6c615>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  listColors = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [60]:
mat1 = np.random.randint(0,5,15).reshape(5,3)
mat2 = np.random.randint(0,5,6).reshape(3,2)

matProduct = np.matmul(mat1,mat2)

print(matProduct)

[[11 16]
 [ 5  9]
 [11 12]
 [ 6 17]
 [ 1  4]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [63]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [64]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

4th and 5th

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [66]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-66-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-66-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
use np.floor() function

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
use the entersection function in numpy library

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
set 'all' keyword to 'ignore' using the np.setter function

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [67]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
use np.datetime64 function

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np

def get_all_dates_in_month(year, month):
  """Returns a NumPy array of all the dates in a month.

  Args:
    year: The year of the month.
    month: The month of the year.

  Returns:
    A NumPy array of all the dates in the month.
  """

  start_date = np.datetime64(f'{year}-{month}-01')
  end_date = np.datetime64(f'{year}-{month+1}-01')

  dates = np.arange(start_date, end_date, dtype='datetime64[D]')

  return dates

# Get all the dates in July 2016
july_2016_dates = get_all_dates_in_month(2016, 7)

# Print the dates
print(july_2016_dates)
# used Bard ai :)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np

def compute_inplace(A, B):
  """Computes ((A+B)*(-A/2)) in place (without copy).

  Args:
    A: A NumPy array.
    B: A NumPy array.

  Returns:
    A NumPy array.
  """

  # Add A and B in place.
  np.add(A, B, out=A)

  # Divide A by 2 in place.
  np.divide(A, 2, out=A)

  # Negate A in place.
  np.negative(A, out=A)

  # Multiply A and B in place.
  np.multiply(A, B, out=A)

  return A

# Create two NumPy arrays
A = np.ones(3)
B = np.ones(3)

# Compute ((A+B)*(-A/2)) in place
computed_array = compute_inplace(A, B)

# Print the computed array
print(computed_array)

# used Bard ai :)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [87]:
listRand = np.random.rand(10) *50
print(listRand)

[46.11697418  0.72267363 37.35407838 29.77675749 18.27113728  9.20081181
 31.27568204 12.43903112 48.51974213 16.23575406]


In [73]:
np.trunc(listRand)

array([ 3., 36.,  3., 46., 47., 48., 32., 48., 30., 37.])

In [74]:
np.fix(listRand)

array([ 3., 36.,  3., 46., 47., 48., 32., 48., 30., 37.])

In [75]:
np.floor(listRand)


array([ 3., 36.,  3., 46., 47., 48., 32., 48., 30., 37.])

In [76]:
listRand //1

array([ 3., 36.,  3., 46., 47., 48., 32., 48., 30., 37.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [81]:
matrix = np.arange(0,5, dtype=np.int32).reshape(5,1)
np.tile(matrix, (1,5))

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]], dtype=int32)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [83]:
def generate_integers():
  for i in range(10):
    yield i

generator = generate_integers()

array = np.fromiter(generator, dtype=np.int32)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [88]:
np.random.rand(10)

array([0.31343426, 0.53278204, 0.39696046, 0.57713674, 0.7553432 ,
       0.9260079 , 0.4695364 , 0.46866136, 0.01786647, 0.01831044])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [93]:
vector = np.random.rand(10)

vector.sort()

print(vector)

[0.05227424 0.15560576 0.29335684 0.31320086 0.34245105 0.40460252
 0.44159118 0.72083919 0.76057222 0.87808042]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)